###### AWS CLOUD FOUNDATION - ALEXSANDRO LECHNER
Description: Criar um Amazon EC2 simples
Resources:
  MinhaInstanciaLaboratorio:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-1a
      ImageId: ami-0ed9277fb7eb570c9
      InstanceType: t3.micro
      Tags:
        - Key: Name
          Value: MinhaInstanciaLaboratorio