Description: Configurar grupo de seguranca
Resources:
  MinhaInstancia:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-1a
      ImageId: ami-0ed9277fb7eb570c9
      InstanceType: t3.micro
      Tags:
        - Key: "Name"
          Value: "WebserverFirewall"
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          yum update -y
          yum install -y httpd.x86_64
          systemctl start httpd.service
          systemctl enable httpd.service
          echo "<h1>Servidor Apache em execucao na instância $(hostname -f)</h1>" > /var/www/html/index.html

  MeuGrupoSeguranca:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Grupo de seguranca para permitir trafego HTTP e SSH"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0